name: Firebase App Distribution

on: push

jobs:
  iOS-Build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Install the build certificate and provisioning profile
#        env:
#          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_BUILD_CERTIFICATE }}
#          BUILD_P12_PASSWORD: ${{ secrets.APPLE_BUILD_CERTIFICATE_PASSWORD }}
#          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_BUILD_PROFILE }}
#          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_TEMPORARY_KEYCHAIN_PASSWORD }}
#        run: |
#          # create variables
#          BUILD_CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
#          BUILD_PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
#          KEYCHAIN_PATH=$RUNNER_TEMP/build_app-signing.keychain-db
#
#          # import certificate and provisioning profile from secrets
#          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $BUILD_CERTIFICATE_PATH
#          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $BUILD_PP_PATH
#
#          # create temporary keychain
#          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
#          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#
#          # import build certificate to keychain
#          security import $BUILD_CERTIFICATE_PATH -P "$BUILD_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
#          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#          security list-keychain -d user -s $KEYCHAIN_PATH
#
#          # apply provisioning profile
#          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
#          cp $BUILD_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Archive xcarchive
        run: xcodebuild -project CodeLab.xcodeproj -scheme CodeLab archive -archivePath build/CodeLab.xcarchive -allowProvisioningUpdates
#
#      - name: Install the export certificate and provisioning profile
#        env:
#          EXPORT_CERTIFICATE_BASE64: ${{ secrets.APPLE_EXPORT_CERTIFICATE }}
#          EXPORT_P12_PASSWORD: ${{ secrets.APPLE_EXPORT_CERTIFICATE_PASSWORD }}
#          EXPORT_PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_EXPORT_PROFILE }}
#          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_TEMPORARY_KEYCHAIN_PASSWORD }}
#        run: |
#          # create variables
#          EXPORT_CERTIFICATE_PATH=$RUNNER_TEMP/export_certificate.p12
#          EXPORT_PP_PATH=$RUNNER_TEMP/export_pp.mobileprovision
#          KEYCHAIN_PATH=$RUNNER_TEMP/export_app-signing.keychain-db
#
#          # import certificate and provisioning profile from secrets
#          echo -n "$EXPORT_CERTIFICATE_BASE64" | base64 --decode -o $EXPORT_CERTIFICATE_PATH
#          echo -n "$EXPORT_PROVISION_PROFILE_BASE64" | base64 --decode -o $EXPORT_PP_PATH
#
#          # create temporary keychain
#          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
#          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#
#          # import build certificate to keychain
#          security import $EXPORT_CERTIFICATE_PATH -P "$EXPORT_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
#          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#          security list-keychain -d user -s $KEYCHAIN_PATH
#
#          # apply provisioning profile
#          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
#          cp $EXPORT_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build/CodeLab.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist -allowProvisioningUpdates